networks:
  cont_net:
    name: inception

volumes:

  db_data:
    name: "mariadb_data"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb_data
      
  wp_data:
    name: "wordpress_data"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress_data

services:

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    env_file: .env
    restart: always
    volumes:
      - wordpress_data:/server/wp_data
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    env_file: .env
    restart: always
    volumes:
      - wordpress_data:/server/wp_data
    depends_on:
      - mariadb
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    env_file: .env
    restart: always
    volumes:
      - mariadb_data:/server/db_data
    networks:
      - inception
