networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb_data   
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress_data

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    env_file: ./.env
    restart: always
    volumes:
      - wordpress_data:/usr/share/webapps
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    env_file: ./.env
    restart: always
    volumes:
      - wordpress_data:/usr/share/webapps
    depends_on:
      mariadb:
        condition: service_healthy
        # restart: true
    networks:
      - inception
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    env_file: ./.env
    restart: always
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping"]
      interval: 10s
      timeout: 20s
      retries: 3
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
