CREATE DATABASE IF NOT EXISTS `${DB_NAME}` CHARACTER SET utf8;

CREATE USER IF NOT EXISTS '${MDB_USER}'@'%' IDENTIFIED BY '${MDB_USER_PASS}';
CREATE USER IF NOT EXISTS '${MDB_ROOT_USER}'@'%' IDENTIFIED BY '${MDB_ROOT_PASS}';

GRANT ALL PRIVILEGES ON `${DB_NAME}`.* TO '${MDB_USER}'@'%';
GRANT ALL PRIVILEGES ON *.* TO '${MDB_ROOT_USER}'@'%';

FLUSH PRIVILEGES;